#!/usr/bin/env bash

parse-gitdiff() {
    # Compare the last 2 commits
    _CURRENT_DIFF=$(git --no-pager diff --name-only HEAD~1..HEAD)

    # Check whether relevant folders got changed
    for package in "${_PACKAGES[@]}"; do
        if [[ "$_CURRENT_DIFF" =~ "$package"/ ]]; then
            _PKG+="$package"
            echo "Detected changes in $package, will push updates to AUR..."
        fi
    done

    if [[ "${#_PKG[@]}" == 0 ]]; then
        echo "No relevant package changes to push found, exiting gracefully." && exit 0
    fi
}

push-aur() {
    for package in "${_PKG[@]}"; do
        _CURRDIR=$(pwd)

        # shellcheck source=/dev/null
        test -f "$_CURRDIR"/"$package"/.CI_CONFIG && source "$_CURRDIR"/"$package"/.CI_CONFIG

        if [[ "$CI_MANAGE_AUR" == 0 ]]; then
            echo "AUR management for $package is disabled in .CI_CONFIG." && continue
        fi

        printf "\nPushing %s to AUR..." "$package"

        _TMPDIR=$(mktemp -d)
        git clone "ssh://aur@aur.archlinux.org/$package.git" "$_TMPDIR"

        rsync --verbose --delete \
            --exclude "interfere.patch" \
            --exclude "prepare" \
            --exclude "PKGBUILD.append" \
            --exclude "PKGBUILD.prepend" \
            --include ".SRCINFO" \
            "$_CURRDIR/$package/" "$_TMPDIR"

        pushd "$_TMPDIR" || echo "Failed to change into $_TMPDIR!"

        # Only push if there are changes
        if ! git diff --exit-code --quiet; then
            git add .
            # Commit and push the changes to our new branch
            git commit -m "chore: update $package" \
                -m "This commit was automatically generated by the CI pipeline." \
                -m "The changelog can be found at https://gitlab.com/garuda-linux/pkgbuilds-aur." \
                -m "See the CI pipeline logs of the corresponding commit for more information."

            # We force push here, because we want to overwrite in case of updates
            git push
        else
            echo "No changes detected, skipping!"
        fi
    done
}

parse-gitdiff
push-aur
